using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApi.Models
{
    public class BookCoverModel
    {
        ///we don't want to expose returned byte[] object to front end caller
        ///But we want to return Name generated by external api

        public string Name { get; set; }
        //public byte[] Content { get; set; }
    }
}
