using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApi.Models
{
    /// <summary>
    /// BookCoverModel which attached with QuoteModel
    /// </summary>
    public class BookCoverModel
    {

        /// <summary>
        /// Name of the BookCoverModel
        /// </summary>
        public string Name { get; set; }

        //we don't want to expose returned byte[] object to front end caller
        //But we want to return Name generated by external api
        //public byte[] Content { get; set; }
    }
}
